#
# REMOVE ME BEFORE MERGE
#

# at this time, "aws" and "azure" are defined targets
# make sure that you ran the prepare.sh / prepare.bat script!
target: gcp

aws:
  region: us-east-1
  availability_zone: us-east-1a
  bucket: bucket-name-goes-here
  # flavor: c5.2xlarge
  flavor: m5zn.metal
  flavor_compute: m5zn.metal
  profile: permission-profile-goes-here
  # when specifying a VPC ID below then this prefix must exist on that VPC!
  public_vpc_ipv4_cidr: 10.0.0.0/16
  enable_ebs_encryption: false
  # leave empty to create a custom VPC / Internet gateway, or provide the IDs
  # of the VPC / gateway to use, they must exist and properly associated.
  # also: an IPv6 CIDR prefix must be associated with the specified VPC
  vpc_id: ""
  gw_id: ""
  spot_instances:
    use_spot_for_controller: false
    use_spot_for_computes: false

azure:
  resource_group: resource-group-name
  size: Standard_D4d_v4
  size_compute: unused_at_the_moment
  storage_account: storage-account-name
  container_name: container-name

gcp:
  # Path to JSON-formatted service account key file.  Not required if using
  # gcloud auth application-default login  Leave empty in this case.
  credentials:
  project: gcp-asigbahgcp-nprd-47930
  region: us-east1
  zone: us-east1-b
  subnet_cidr: 10.10.0.0/16
  proxy_subnet_cidr: 10.11.1.0/24
  bucket: bah-machine-images
  machine_type: n2-highmem-2
  #compute_machine_type: n2-standard-4
  compute_machine_type: n2-highmem-32
  #compute_machine_type: n2-highmem-4
  spot_compute_machine_type: n2-highmem-4
  number_of_spot_compute_nodes: 1
  # Machines will inherit the SSH keys from project's metadata for all users unless you provide below
  # <user>:<ssh public key>
  # e.g. ssh_key: "cml:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGDAqIBESzn9J9rdSLarhyU6GNycV+43DkdkNzSgfLrP"
  ssh_key:
  load_balancer_fqdns: 
    - becomingahacker.com
    - labs.becomingahacker.com
  dns_zone_name: becomingahacker-com
  controller_image_family: cloud-cml-controller-amd64
  compute_image_family: cloud-cml-compute-amd64

common:
  disk_size: 128
  controller_hostname: cml-controller
  key_name: ssh-key-name
  allowed_ipv4_subnets:
    # GCE cml-subnet
    - "10.10.0.0/16"
    # GCE Health Chekers
    - "35.191.0.0/16"
    - "209.85.152.0/22"
    - "209.85.204.0/22"
    # Google Front End
    - "34.96.0.0/16"
    - "34.127.0.0/16"
    # RTP NAT pool
    - "173.38.117.64/26"
    # cmm
    - "23.116.118.232/29"
    # cmm
    - "99.69.22.234/32"
    # ASIG
    - "64.100.197.0/24"
    - "64.100.220.0/23"
  enable_patty: false

cluster:
  enable_cluster: true
  # No longer used, see the secret manager section below
  #secret: your-secret-password
  allow_vms_on_controller: false
  number_of_compute_nodes: 0
  compute_hostname_prefix: cml-compute
  compute_disk_size: 128

secret:
  # At this time, 'vault', 'conjur' and 'dummy' are supported secrets managers.
  # Make sure that you also run the prepare.sh / prepare.bat script, otherwise
  # a 'raw_secret' will be used.  If 'raw_secret' is not defined, a random
  # password will be used.
  # https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password
  #manager: vault
  manager: conjur
  #manager: dummy

  conjur:

  vault:
    # Only the v2 version of the key value secret engine is supported
    # https://developer.hashicorp.com/vault/docs/secrets/kv/kv-v2
    kv_secret_v2_mount: secret
    # Set this to true to prevent the creation of ephemeral child token used by this provider.
    skip_child_token: true

  # These are the secrets that will be used by the CML instances.  This key
  # gets mapped to the main configuration under 'secrets'.  The values are
  # filled in by the secrets manager and are accessible using the 'secret'. For
  # example, the 'app' password is accessed using 'secrets.app.secret'. The
  # SmartLicense token is accessed using 'secrets.smartlicense_token.secret'.
  secrets:
    app:
      username: admin
      # Used with dummy secret manager.  If unspecified, a random password will
      # be generated. You need to escape special chars:
      #raw_secret: '\"!@$%'
      #raw_secret: your-secret-password
      # Path to secret, used with both Vault and Conjur:
      path: sto/becomingahacker/secret/common/becomingahacker.com/prod/host/cml-0.becomingahacker.com/admin_password
      # Used with Vault only:
      #field: secret

    sys:
      username: sysadmin
      # Used with dummy secret manager.  If unspecified, a random password will
      # be generated.
      #raw_secret: your-secret-password
      # Path to secret, used with both Vault and Conjur:
      path: sto/becomingahacker/secret/common/becomingahacker.com/prod/host/cml-0.becomingahacker.com/sysadmin_password
      # Used with Vault only:
      #field: secret

    smartlicense_token:
      # Only used with dummy secret manager
      raw_secret: your-smart-licensing-token
      # Path to secret, used with both Vault and Conjur:
      path: sto/becomingahacker/secret/common/becomingahacker.com/prod/host/cml-0.becomingahacker.com/license_token
      # Used with Vault only:
      #field: token

    cluster:
      # Used with dummy secret manager.  If unspecified, a random password will
      # be generated.
      #raw_secret: your-secret-password
      # Path to secret, used with both Vault and Conjur:
      path: sto/becomingahacker/secret/common/becomingahacker.com/prod/host/cml-0.becomingahacker.com/cluster_secret
      # Used with Vault only:
      #field: secret

app:
  # **No longer used, see the secret manager section above**
  #user: admin
  #pass: your-secret-password
  software: cml2_2.7.0-4_amd64-20.pkg
  # The list must have at least ONE element, this is what the dummy is for in
  # case 00- and 01- are commented out!
  customize:
    # - 00-patch_vmx.sh
    - 99-dummy.sh

license:
  flavor: CML_Enterprise
  # **No longer used, see the secret manager section above**
  #token: your-smart-licensing-token
  # Unless you have additional node licenses available, leave this at zero
  nodes: 0

# Select the reference platforms needed by un-/commenting them. The selected
# reference platforms will be copied from the specified cloud storage and must
# be available prior to starting an instance. Ensure that each definition has
# also a corresponding image! A smaller selection: less copying, faster bring-up
# time!
refplat:
  definitions:
    - alpine
    # - alpine-trex
    # - alpine-wanem
    # - asav
    # - cat8000v
    # - cat9000v-q200
    # - cat9000v-uadp
    # - cat-sdwan-edge
    # - cat-sdwan-controller
    # - cat-sdwan-manager
    # - cat-sdwan-validator
    # - cat-sdwan-vedge
    # - csr1000v
    # - desktop
    - iol-xe
    - ioll2-xe
    - iosv
    - iosvl2
    # - iosxrv9000
    # - nxosv9000
    - server
    - ubuntu
  images:
    - alpine-base-3-19-1
    # - alpine-trex-3-19-1
    # - alpine-wanem-3-19-1
    # - asav-9-20-2
    # - cat8000v-17-13-01a
    # - cat9000v-q200-17-12-01prd9
    # - cat9000v-uadp-17-12-01prd9
    # - cat-sdwan-edge-17-13-01a
    # - cat-sdwan-controller-20-13-1
    # - cat-sdwan-manager-20-13-1
    # - cat-sdwan-validator-20-13-1
    # - cat-sdwan-vedge-20-13-1
    # - csr1000v-17-03-068a
    # - desktop-3-19-1-xfce
    - iol-xe-17-12-01
    - ioll2-xe-17-12-01
    - iosv-159-3-m8
    - iosvl2-2020
    # - iosxrv9000-7-11-1
    # - nxosv9300-10-4-2-f
    - server-tcl-14-0
    - ubuntu-22-04-20240126
