#
# This file is part of Cisco Modeling Labs
# Copyright (c) 2019-2023, Cisco Systems, Inc.
# All rights reserved.
#

lb_fqdn: labs.becomingahacker.com
hostname: cml-0.becomingahacker.com
domain_name: becomingahacker.com

aws:
  region: us-east-2
  vpc: cmm-vpc
  availability_zone: us-east-2a
  subnet: cmm-subnet-public1-us-east-2a
  mgmt_cidrs:
    v4:
      - 173.38.117.64/26	# rtp-corp-nat-pool
      - 99.69.22.234/32   # cmm-home
  bucket: bah-machine-images
  #flavor: c5n.metal
  flavor: c5d.xlarge
  profile: CiscoModelingLabs
  key_name: bootstrap_ssh
  disk_size: 64

secrets:
  - &app_password  sto/becomingahacker/secret/common/becomingahacker.com/prod/host/cml-0.becomingahacker.com/admin_password
  - &sys_password  sto/becomingahacker/secret/common/becomingahacker.com/prod/host/cml-0.becomingahacker.com/sysadmin_password
  - &license_token sto/becomingahacker/secret/common/becomingahacker.com/prod/host/cml-0.becomingahacker.com/license_token

app:
  user: admin
  pass: *app_password
  # need to escape special chars:
  # pass: '\"!@$%'
  deb: cml2_2.6.1-11_amd64.deb
  # list must have at least ONE element, this is what the dummy is for in case
  # 00- and 01- are commented out!
  customize:
    - 00-patch_vmx.sh
    # - 01-patty.sh
    - 02-libvirt_default_network.sh
    # - 99-dummy.sh

sys:
  user: sysadmin
  pass: *sys_password

license:
  flavor: CML_Enterprise
  token: *license_token
  # unless you have additional nodes, leave this at zero
  nodes: 0

# select the ones needed by un-/commenting them. The selected
# reference platforms will be copied from the specified bucket
# and must be available prior to starting an instance.
refplat:
  definitions:
    - alpine
    - alpine-trex
    - alpine-wanem
    #- asav
    #- cat8000v
    #- cat9000v-s1
    #- csr1000v
    - desktop
    - iosv
    - iosvl2
    #- iosxrv9000
    #- nxosv9000
    #- server
    #- ubuntu
  images:
    - alpine-3-16-2-base
    - alpine-3-16-2-trex
    - alpine-3-16-2-wanem
    #- asav-9-18-2
    #- cat8000v-17-09-01a
    #- cat9000v-s1-17.10.01prd7
    #- csr1000v-17-03-06
    - desktop-3-16-2-xfce
    - iosv-159-3-m6
    - iosvl2-2020
    #- iosxrv9000-7-7-1
    #- nxosv9300-10-3-1-f
    #- server-tcl-13-1
    #- ubuntu-22-04-20221028
