#
# This file is part of Cisco Modeling Labs
# Copyright (c) 2019-2023, Cisco Systems, Inc.
# All rights reserved.
#

#
# This is the configuration file for the CML bootstrap script.
#

# Load balancer fully qualified domain name.  Uses a CNAME to point to the load balancer.
lb_fqdn: labs.becomingahacker.com
# Load balancer alias. Uses an A record to point to the load balancer.  Set to 'null' to disable.
lb_fqdn_alias: becomingahacker.com
# Cisco Modeling Labs host.  This is used for Cockpit (tcp/9090) and SSH (tcp/22) access.
hostname: cml-0.becomingahacker.com
# Route53 zone name
domain_name: becomingahacker.com

# AWS configs
aws:
  region: us-east-2
  vpc: cmm-vpc
  availability_zone: us-east-2a
  subnet: cmm-subnet-public1-us-east-2a

  # CIDRs for accessing management endpoints such as Cockpit and SSH for the host (tcp/1122)
  mgmt_cidrs:
    v4:
      - description: "cmm-home-rtr" 
        cidr: 99.69.22.234/32
      - description: "cmm-home-blk" 
        cidr: 23.116.118.232/29
      - description: CSCO SJC1	
        cidr: 128.107.241.160/27
      - description: CSCO SJC2 
        cidr: 173.36.240.160/27
      - description: CSCO RTP1
        cidr: 173.38.117.64/27 
      - description: CSCO RTP2
        cidr: 64.102.249.0/27
      - description: CSCO RDCN1
        cidr: 72.163.2.224/27 
      - description: CSCO RCDN2
        cidr: 173.37.200.0/27 
      - description: CSCO ALLN1
        cidr: 173.36.120.0/28
      - description: CSCO ALLN2
        cidr: 173.36.113.96/27 
      - description: "NCREN-CIDR3"
        cidr: 204.84.0.0/15
      - description: "AT&T SIS-80-4-2012"
        cidr: 107.192.0.0/11

  # CIDRs for accessing production (HTTPS, SSH console server tcp/22)
  prod_cidrs:
    v4:
      - description: "cmm-home-rtr" 
        cidr: 99.69.22.234/32
      - description: "cmm-home-blk" 
        cidr: 23.116.118.232/29
      - description: "NET-76-182-0-0-1 Charter"
        cidr: 76.182.0.0/17
      - description: "AT&T SIS-80-4-2012"
        cidr: 107.192.0.0/11
      - description: "NCSU 1"
        cidr: 152.1.0.0/16
      - description: "NCSU 2"
        cidr: 152.7.0.0/16
      - description: "NCSU 3"
        cidr: 152.14.0.0/16
      - description: "NCREN-CIDR3"
        cidr: 204.84.0.0/15
      - description: "NETBLK-CISCO-GEN-6 for use in San Jose, EMEA, and RTP"
        cidr: 64.100.0.0/14
      - description: "NETBLK-CISCO-GEN-6 for use in AsiaPac"
        cidr: 64.104.0.0/16
      - description: "CISCO-GEN-8"
        cidr: 173.36.0.0/14

  # The S3 bucket where reference platforms are stored, along with scripts to set up CML
  bucket: bah-machine-images

  # TODO cmm - CiscoModelingLabs role must not be able to access this bucket
  # Must be globally unique and updated in terraform.tf backend config
  tfstate_bucket: cml-tfstate-bucket
  tfstate_key: cloud-cml/terraform.tfstate

  # The EC2 instance type to use.  Use a .metal type for /dev/kvm support.
  #flavor: z1d.metal
  #flavor: c5n.metal
  flavor: c5d.xlarge

  # IAM Role for EC2 host to assume
  profile: CiscoModelingLabs

  key_name: bootstrap_ssh
  disk_size: 64

secrets:
  - &app_password  sto/becomingahacker/secret/common/becomingahacker.com/prod/host/cml-0.becomingahacker.com/admin_password
  - &sys_password  sto/becomingahacker/secret/common/becomingahacker.com/prod/host/cml-0.becomingahacker.com/sysadmin_password
  - &license_token sto/becomingahacker/secret/common/becomingahacker.com/prod/host/cml-0.becomingahacker.com/license_token

app:
  user: admin
  pass: *app_password
  deb: cml2_2.6.1-11_amd64.deb
  # list must have at least ONE element, this is what the dummy is for in case
  # the test is empty
  customize:
    - 00-patch_vmx.sh
    # - 01-patty.sh
    - 02-libvirt_default_network.sh
    - 03-training_site.sh
    # - 99-dummy.sh

sys:
  user: sysadmin
  pass: *sys_password

license:
  flavor: CML_Enterprise
  token: *license_token
  # Unless you have additional nodes, leave this at zero.
  # You can bump this up later on if you need to add more nodes.
  nodes: 0

# select the ones needed by un-/commenting them. The selected
# reference platforms will be copied from the specified bucket
# and must be available prior to starting an instance.
refplat:
  definitions:
    - alpine
    - alpine-trex
    - alpine-wanem
    #- asav
    #- cat8000v
    #- cat9000v-s1
    #- csr1000v
    - desktop
    - iosv
    - iosvl2
    #- iosxrv9000
    #- nxosv9000
    #- server
    #- ubuntu
  images:
    - alpine-3-16-2-base
    - alpine-3-16-2-trex
    - alpine-3-16-2-wanem
    #- asav-9-18-2
    #- cat8000v-17-09-01a
    #- cat9000v-s1-17.10.01prd7
    #- csr1000v-17-03-06
    - desktop-3-16-2-xfce
    - iosv-159-3-m6
    - iosvl2-2020
    #- iosxrv9000-7-7-1
    #- nxosv9300-10-3-1-f
    #- server-tcl-13-1
    #- ubuntu-22-04-20221028
